theme: jekyll-theme-minimal
title: Quan Vu | Software Engineer
logo: /assets/img/logo.png
description: Learn and practice Python/Flask/Django, Backend with RestfulAPI & Graphql Microservices, Kubernetes, Docker and more...
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
©
